### ISSUE TITLE
Variadic signature doesnt type check

### ISSUE THREAD

**Issue by katywings** [konfirm/node-polymorphic#2]
Hey hey

I started using your polymorphic lib, which is really useful! However I noticed some flaws. (The second one is propably just nice-to-have though)

Problem Demo: http://www.webpackbin.com/41e7Ro5Zf
The variadic signature doesnt type check correctly!

As the demo shows: `number, ...` currently works with the function call `('test', 1, 2)`
But I think that shouldnt work!

Thanks for your help in advance!

**Comment by rspieker** [comment]
Thank you for reporting this issue! I will look into it as it should not behave this way indeed.

**Comment by rspieker** [comment]
The fix for this and #3 are now published as [version 1.3.0](https://www.npmjs.com/package/polymorphic)

**Comment by katywings** [comment]
That was fast! Thx a lot :).

(But its a pity: after I added the issues, I noticed your choosen license GPL. To my knowledge this license would require me to license my work with GPL as well, so I basically cant use Poly ;)

**Comment by rspieker** [comment]
You're welcome!

You shouldn't worry too much about the GPL license, it does not require your code to be GPL'ed aswel, only that you provide Polymorphic as GPL with its license (and you can do that on request, if that ever happens). It's perfectly fine to have a commercial project which uses GPL without open sourcing the entire project.

**Comment by katywings** [comment]
Thanks for your fast feedback! I don't want to start a discussion / debate :) here! But from my point of view, it would just be a risk to use a GPL licensed javascript lib (for client side projects)(https://www.nczonline.net/blog/2015/12/why-im-not-using-your-open-source-project/)

Sidenote: It looks like GPL isn't a problem for serverside Javascript, but using a GPL lib for the client side is a gray area :/, because that code gets distributed to other users)

> You must cause any work that you distribute or publish, that in whole or in part contains or is derived from the Program or any part thereof, to be licensed as a whole at no charge to all third parties under the terms of this License.

**Comment by rspieker** [comment]
I never thought it to be an issue, but I'll look into changing the license so it does not form a barrier for usage in whatever way people want. Thanks for bringing this to my attention! ;-)

**Comment by rspieker** [comment]
As of v1.4.0 node-polymorphic is licensed under the MIT license.
