### ISSUE TITLE
Function not called with this

### ISSUE THREAD

**Issue by katywings** [konfirm/node-polymorphic#3]
This is a nice to have feature:

```js
var fun = polymorphic();
fun.signature('number', function(num) {
    console.log(this);
});
fun.call('so funny',2);
// logs window or so
// should log "so funny"
```

Is this technically even possible with the current polymorphic approach?

**Comment by rspieker** [comment]
Thanks for suggesting to preserve other `this`-contexts. I've done a quick test and it should be a simple change.
