### ISSUE TITLE
Consider changing OSS license

### ISSUE THREAD

**Issue by rspieker** [konfirm/node-polymorphic#4]
It appears as if there may be some reluctance in using polymorphic in (client-side) projects due to the GPL(2) license. The sentiment is that it requires all code using the library to be GPL'ed aswel.

If this is indeed the case, the license should be changed.

[jQuery changed from dual license GPL/MIT to only MIT](https://blog.jquery.com/2012/09/10/jquery-licensing-changes/)
[Reading material](http://choosealicense.com/appendix/)

**Comment by rspieker** [comment]
Some more reading:
[Jeff Atwood explains licenses](https://blog.codinghorror.com/pick-a-license-any-license/)
[Smashing Magazine explains licenses](https://www.smashingmagazine.com/2010/03/a-short-guide-to-open-source-and-similar-licenses/)

The GPL(v2) indeed demands any derivative work to be GPL'ed, which is (as mentioned in #2) not practical for use in client-side code.

The license should allow any kind of usage - which is why the project is on GitHub in the first place - without any restrictions other than a reference where the code originated from.
This seems to be covered by BSD, MIT, ISC and Apache Licence, where the latter even explicitly deals with (possible) patents.

**Comment by rspieker** [comment]
Changed to the MIT license as of v1.4.0, preserved the GPLv2 as a separate branch

**Comment by katywings** [comment]
P.S. You are crazy :D
P.P.S in a good way xD
P.P.P.S the license change is huge! Thx a lot <3
